name: Release `spandrel`

on:
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  save-compiled-library:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: sh scripts/install.sh
      - name: Build packages
        run: sh scripts/build.sh
      - name: Upload compiled library as artifact
        uses: actions/upload-artifact@v3
        with:
          name: spandrel-dist
          path: libs/spandrel/dist/
