name: Release `spandrel`

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  save-compiled-library:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: sh scripts/install.sh
      - name: Build packages
        run: |
          sh scripts/build.sh
          # Simplify the folder structure
          mkdir -p dist/
          tar -xvf libs/spandrel/dist/spandrel-0.4.0.tar.gz -C dist/ --strip-components=2
      - name: Upload compiled library as artifact
        uses: actions/upload-artifact@v3
        with:
          name: spandrel-dist
          path: dist/
